// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: gateway.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnID        uint64                 `protobuf:"varint,1,opt,name=connID,proto3" json:"connID,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayRequest) Reset() {
	*x = GatewayRequest{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayRequest) ProtoMessage() {}

func (x *GatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayRequest.ProtoReflect.Descriptor instead.
func (*GatewayRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayRequest) GetConnID() uint64 {
	if x != nil {
		return x.ConnID
	}
	return 0
}

func (x *GatewayRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GatewayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayResponse) Reset() {
	*x = GatewayResponse{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayResponse) ProtoMessage() {}

func (x *GatewayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayResponse.ProtoReflect.Descriptor instead.
func (*GatewayResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GatewayResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\aservice\"<\n" +
	"\x0eGatewayRequest\x12\x16\n" +
	"\x06connID\x18\x01 \x01(\x04R\x06connID\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"7\n" +
	"\x0fGatewayResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\x82\x01\n" +
	"\aGateway\x12<\n" +
	"\aDelConn\x12\x17.service.GatewayRequest\x1a\x18.service.GatewayResponse\x129\n" +
	"\x04Push\x12\x17.service.GatewayRequest\x1a\x18.service.GatewayResponseB\fZ\n" +
	"./;serviceb\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gateway_proto_goTypes = []any{
	(*GatewayRequest)(nil),  // 0: service.GatewayRequest
	(*GatewayResponse)(nil), // 1: service.GatewayResponse
}
var file_gateway_proto_depIdxs = []int32{
	0, // 0: service.Gateway.DelConn:input_type -> service.GatewayRequest
	0, // 1: service.Gateway.Push:input_type -> service.GatewayRequest
	1, // 2: service.Gateway.DelConn:output_type -> service.GatewayResponse
	1, // 3: service.Gateway.Push:output_type -> service.GatewayResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
